### PR TITLE
Add FORTNIGHTLY

### PR DESCRIPTION
**Pull request by drasco64**
Biweekly payments are 26 per year

### CODE REVIEW

**Comment by roniemartinez** [comment]
Thanks for your PR!

However, "biweekly" has 2 definitions, "Every two weeks" or "Twice a week" ([wiktionary](https://en.wiktionary.org/wiki/biweekly), [Merriam-Webster](https://www.merriam-webster.com/dictionary/biweekly)) which makes things confusing.

In this library, I've chosen it to be "Twice a week". I would keep it to make sure no breaking changes for people already using it.

**Comment by drasco64** [comment]
I need the every 2 weeks version, would you consider an additional enum for BIWEEKLY_ALT or something or should I just track my own version?

**Comment by roniemartinez** [comment]
@drasco64 How about “Fortnightly”?

**Comment by drasco64** [comment]
Works for me

**Comment by roniemartinez** [comment]
Thanks @drasco64

**Pull request merged**
